import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';
import { GameLayout } from '@/components/GameLayout';
import { HudLabel } from '@/components/ui';
import { scenarios } from '@/data/scenarios';
import { colors, radius } from '@/theme';

const whiteHouse = require('../../../assets/video-page.png');
export default function BriefingScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const scenario = scenarios.find((item) => item.id === id) ?? scenarios[0]; return <GameLayout><View style={styles.content}><ImageBackground source={whiteHouse} resizeMode="cover" style={styles.hero} imageStyle={styles.image}><Pressable accessibilityRole="button" accessibilityLabel="Back to scenarios" onPress={() => router.replace('/game/scenarios')} style={styles.back}><Ionicons name="arrow-back" size={25} color={colors.text} /></Pressable><View style={styles.shade}><HudLabel>Scenario Briefing</HudLabel><Text style={styles.title}>{scenario.title}</Text><Text style={styles.body}>{scenario.briefing}</Text><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/game/cinematic', params: { id: scenario.id } })} style={styles.button}><LinearGradient colors={['rgba(11,69,84,0.9)', 'rgba(5,41,55,0.93)', 'rgba(10,73,87,0.88)']} locations={[0, 0.55, 1]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.buttonFill}><Text style={styles.buttonText}>Start Simulation</Text></LinearGradient></Pressable></View></ImageBackground></View></GameLayout>; }
const styles = StyleSheet.create({ content: { flex: 1, padding: 18 }, hero: { flex: 1, overflow: 'visible', borderRadius: radius.lg, backgroundColor: '#12233F' }, image: { opacity: 0.65, borderRadius: radius.lg }, back: { position: 'absolute', zIndex: 2, top: -24, left: 14, width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#07101F' }, shade: { flex: 1, overflow: 'hidden', borderRadius: radius.lg, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(2,6,23,0.48)', paddingHorizontal: '18%' }, title: { alignSelf: 'stretch', color: colors.text, fontSize: 34, lineHeight: 40, textAlign: 'center', fontStyle: 'italic', fontWeight: '900', marginTop: 7 }, body: { color: '#E1E7F0', textAlign: 'center', fontSize: 15, lineHeight: 22, marginTop: 16 }, button: { width: 250, height: 62, overflow: 'hidden', borderRadius: 30, borderWidth: 1, borderColor: '#83B7C6', marginTop: 24 }, buttonFill: { flex: 1, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: colors.cyan, fontSize: 18, fontWeight: '900', includeFontPadding: false } });
