import { router, useLocalSearchParams } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { useMemo, useState } from 'react';
import { ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';
import { GameLayout } from '@/components/GameLayout';
import { questionsByScenario } from '@/data/questions';
import { scenarios } from '@/data/scenarios';
import { colors, radius } from '@/theme';

const whiteHouse = require('../../../assets/video-page.png');
export default function DecisionScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const scenario = scenarios.find((item) => item.id === id) ?? scenarios[0]; const [step, setStep] = useState(0); const [selected, setSelected] = useState<string>();
  const questions = useMemo(() => questionsByScenario[scenario.id] ?? questionsByScenario['iraq-war'], [scenario.id]);
  const goNext = () => { if (!selected) return; if (step === 2) router.replace('/game/dna'); else { setStep((value) => value + 1); setSelected(undefined); } };
  return <GameLayout><ImageBackground source={whiteHouse} resizeMode="cover" style={styles.background} imageStyle={styles.image}><View style={styles.overlay}><Text style={styles.kicker}>DECISION {step + 1} / 3 · {scenario.title.toUpperCase()}</Text><Text style={styles.question}>{questions[step].prompt}</Text><View style={styles.grid}>{questions[step].answers.map((answer, index) => { const choiceId = step + '-' + index; const isSelected = selected === choiceId; return <Pressable key={choiceId} onPress={() => setSelected(choiceId)} style={[styles.choice, isSelected && styles.selected]}>{isSelected && <LinearGradient pointerEvents="none" colors={['rgba(35,57,74,0.95)', '#00ACC4', 'rgba(14,65,78,0.96)']} locations={[0, 0.52, 1]} start={{ x: 0, y: 0.1 }} end={{ x: 1, y: 0.9 }} style={styles.selectedGlow} />}<Text style={[styles.choiceText, isSelected && styles.selectedText]}>{answer}</Text></Pressable>; })}</View><View style={styles.bottom}><View style={styles.progress}>{[0, 1, 2].map((item) => <View key={item} style={[styles.progressPart, item <= step && styles.progressActive]} />)}</View><Pressable disabled={!selected} onPress={goNext} style={[styles.continue, !selected && styles.continueDisabled]}><Text style={styles.continueText}>{step === 2 ? 'Analyze Decision  →' : 'Continue  →'}</Text></Pressable></View></View></ImageBackground></GameLayout>;
}
const styles = StyleSheet.create({ background: { flex: 1, backgroundColor: '#020617' }, image: { opacity: 0.78 }, overlay: { flex: 1, backgroundColor: 'rgba(2,6,23,0.62)', padding: 24 }, kicker: { color: colors.cyan, fontWeight: '800', fontSize: 10, letterSpacing: 1.1, includeFontPadding: false }, question: { color: colors.text, fontSize: 21, fontWeight: '700', lineHeight: 27, includeFontPadding: false, maxWidth: 680, marginTop: 10, marginBottom: 14 }, grid: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', alignContent: 'center', justifyContent: 'center', gap: 12, paddingHorizontal: '7%' }, choice: { width: '43%', minHeight: 68, borderRadius: radius.md, overflow: 'hidden', borderWidth: 1, borderColor: '#D1D8E4', backgroundColor: 'rgba(15,23,42,0.92)', padding: 14, justifyContent: 'center' }, selected: { borderWidth: 2, borderColor: '#E9F8FF', backgroundColor: '#063F4E' }, selectedGlow: { ...StyleSheet.absoluteFill }, choiceText: { color: colors.text, fontSize: 13, fontWeight: '500', lineHeight: 18, includeFontPadding: false, textAlign: 'center', zIndex: 1 }, selectedText: { color: '#F7FCFF', fontWeight: '800' }, bottom: { flexDirection: 'row', alignItems: 'center', gap: 18 }, progress: { flex: 1, height: 6, flexDirection: 'row', gap: 5 }, progressPart: { flex: 1, backgroundColor: '#162238', borderRadius: 5 }, progressActive: { backgroundColor: colors.yellow }, continue: { minWidth: 140, paddingHorizontal: 18, height: 40, borderRadius: 20, backgroundColor: '#083C4A', justifyContent: 'center', alignItems: 'center' }, continueDisabled: { backgroundColor: colors.surface }, continueText: { color: colors.cyan, fontSize: 12, fontWeight: '800', includeFontPadding: false } });
