import { router } from 'expo-router';
import { FlatList, ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';
import { GameLayout } from '@/components/GameLayout';
import { HudLabel } from '@/components/ui';
import { scenarios } from '@/data/scenarios';
import { colors, radius } from '@/theme';

export default function ScenariosScreen() {
  return <GameLayout onBack={() => router.replace('/')}><View style={styles.content}><Text style={styles.title}>Scenarios</Text><HudLabel>Choose A Scenario And Ask Yourself, “If You Were In That Situation, What Would You Do?”</HudLabel><Text style={styles.count}>30 Scenarios</Text><FlatList horizontal data={scenarios} keyExtractor={(item) => item.id} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.cards} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Start ${item.title}`} onPress={() => router.push({ pathname: '/game/briefing', params: { id: item.id } })} style={({ pressed }) => [styles.card, pressed && styles.cardPressed]}><ImageBackground source={item.image} style={styles.cardImage} imageStyle={styles.cardImageRadius}><View style={styles.imageShade} /><View style={styles.cardContent}><Text style={styles.duration}>◷ {item.duration}</Text><Text style={styles.cardTitle}>{item.title}</Text><Text numberOfLines={4} style={styles.teaser}>{item.teaser}</Text><View style={styles.start}><Text style={styles.startText}>Start</Text></View></View></ImageBackground></Pressable>} /></View></GameLayout>;
}

const styles = StyleSheet.create({ content: { flex: 1, paddingHorizontal: 28, paddingTop: 24, paddingBottom: 12 }, title: { color: colors.text, fontSize: 25, fontWeight: '800', includeFontPadding: false, marginBottom: 10 }, count: { color: colors.muted, marginTop: 15, marginBottom: 10, fontSize: 13, fontWeight: '800', includeFontPadding: false }, cards: { gap: 16, paddingRight: 30 }, card: { width: 264, height: 210, borderRadius: radius.lg, borderWidth: 1, borderColor: '#263A55', overflow: 'hidden' }, cardPressed: { opacity: 0.78, borderColor: colors.cyan }, cardImage: { flex: 1 }, cardImageRadius: { borderRadius: radius.lg }, imageShade: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(2,6,23,0.43)' }, cardContent: { flex: 1, padding: 15 }, duration: { color: colors.cyan, fontSize: 10, fontWeight: '800', letterSpacing: 0.5, includeFontPadding: false }, cardTitle: { color: colors.text, fontSize: 15, fontWeight: '900', fontStyle: 'italic', includeFontPadding: false, marginTop: 8 }, teaser: { color: '#F1F5F9', fontSize: 12, lineHeight: 16, includeFontPadding: false, marginTop: 7, paddingRight: 2 }, start: { marginTop: 'auto', alignSelf: 'flex-end', minWidth: 76, paddingHorizontal: 16, height: 34, borderRadius: 17, backgroundColor: 'rgba(0,75,94,0.9)', borderWidth: 1, borderColor: '#73B7C8', alignItems: 'center', justifyContent: 'center' }, startText: { color: colors.cyan, fontSize: 12, fontWeight: '900', includeFontPadding: false } });
